CREATE TABLE IF NOT EXISTS shared_file_urls (
    id SERIAL PRIMARY KEY,
    file_id UUID NOT NULL REFERENCES files(id),
    url VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);