version: "3.8"

services:
  api:
    build: .
    image: filesms/api
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=filesms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@host.docker.internal:5432/filesms?sslmode=disable", "up"]
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
